threads=10
ramp_up=5
duration=30
host=localhost
port=9701
protocol=http
path=/v1/rag/similar/5?limit=4
token=3e86613c-3535-4a8c-b275-9ea8f20c5ac1
connect_timeout=10000
response_timeout=30000
jmeter.save.saveservice.output_format=csv
jmeter.save.saveservice.print_field_names=true
jmeter.save.saveservice.timestamp_format=ms
jmeter.save.saveservice.time=true
jmeter.save.saveservice.label=true
jmeter.save.saveservice.successful=true
jmeter.save.saveservice.thread_name=true
jmeter.save.saveservice.response_code=true
jmeter.save.saveservice.response_message=true
jmeter.save.saveservice.data_type=true
jmeter.save.saveservice.bytes=true
jmeter.save.saveservice.sent_bytes=true
jmeter.save.saveservice.connect_time=true
jmeter.save.saveservice.latency=true
